version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432

  mbb:
    image: koloooo/mbb:latest
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD:
      DB_NAME: postgres
      APP_USER: mbb
      APP_USER_PASSWORD: Pass00
      GIN_MODE: release
    depends_on:
      - db
