ports:
- port: 8080

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'init script'

vscode:
  extensions:
    - ms-vscode.Go@0.11.9:VugxNlIkbA15bsrTzmC3vQ==