language: go
go:
  - 1.13.x
services:
  - docker
before_install:
  - docker run -d -p 127.0.0.1:5432:5432 postgres
script:
  - make test-backend
after_success:
  - cd ..
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t koloooo/mbb:latest .
  - docker push koloooo/mbb:latest
env:
  global:
    - secure: BQoc3X/RHI+fb+tKSIRGuoOgZ3bmtRYE6d+sPbjwJlcjG548X18aChsgluo62jv4In4dLr1dJpoj4/4GATG+sBGry4FvYmms2q5oe31Z3FPwreOnCen3GYjJtZ612TOLvgplb8hJRPGhJdyv709i6roMfPzfyrOEkXqVFqakC/l06n0JzE7dYL+1Rf9okqw1gl76DThLZBuYyGi2wXemsqBx+sEkmHao4kkvJ3S7odkXBkoH48cmmbMr9iPBoETAsC56yFVTXzywPAgVgrqsfvVMfkcMcwGafRBcSNjqLT0+XydcHGr4uQpV0o0rT7dHnV4mqYj7CWBosAFQqtROK4mQgyjieV+MYz027GVirHWpDyDW23fX5YH1RNop8PCuzupB2rYu+2+zmFuEsfmRuiwlNMtfeOjPzK7JjBvSzHtekeLz6lGkjNaPldze2y7Zf5d/2HSDA7UWWVcXl0f/D2s8xI6Z82/d82uyGvo5g8DwW/hPL59nTMrjDun94NtS2SWwU6NNQX8kQHYuaEacu9TB4LYcF3GDdWxHXC5GsgJCuLgRlBaz0+EdmVCkxJ41b3j99hkbNmsNpVKzrd0XDBCDUOeCcmyLPZXyve//rL9Ww15WpxGqfn3Ec2uUgOiAldnomFXxR/RGkXyVQbCaaaVWBS5Tn9dEXxnsAu4z6QU=
    - secure: NF+p5fNwbmVYyv+JcKnEQtAEWcVNxuS+EakuG0j2etSHZPdcQ/s3emJ3eOOi1psEBwkXMiom0NjrtbGuLk2J3D9mZT/BfC5PPNWzaXSfrVQb0dq7O2tUPGghly5StXydT3tW0DelBt9r22oX29IXaK06yTp9bAPU/mxSlSlAFPQVr+GmcL+Po8ezjnyjB0SracAXXHUEJTjPst54mo5HNXAO2gR8PnRGAqtv/+fUYIlxx4FNNqiPWWZ3K0+zniJV0DwGwVcQwHYXYMWbiAf/9bzWW2oK0SbOzC8oxAGEys2tUTD2UPrANbtJpDbthPR9mRKY5yuXL8ocyMTUf8Y2jbqv1OZEgZdy0OnWqL0fZ4vUxu3+OoUy3uf2sJAofqfsHRdOQGj1d8LELLuItXmOKTRasKLQ8Odc9Bcf0RaWVWATKbmo+7QLGzutdPd+whs5zw6a/cznMx2P3xDa5mMzexH16RSfU5pBtMX+beVHoISke7L+qRPQxzsAPMi65PE2bfylhkbe8njOfH+jba/6q3/JNXBBQH5gFrCptOcP/qNQao/fF7YARty2I9ZdCVBYE4dzeRfPWZ4N5c9MmRPMwFOY+YCXVvn9CmFAsrYaObeyARv7TlbQSty2AksKwUExA81syalrXIjr9P3asqSQmM4mAiA3s+K0PhyyI88yPgA=
