language: go

go:
  - 1.13.x

services:
  - docker

before_install:
  - docker run -d -p 127.0.0.1:5432:5432 postgres

install:
  - cd backend
  - go get

script:
  - go test -v ./...

after_success:
  - cd ..
  - ./increment_version.sh -m "$(cat version)" > version
  - docker build -t koloooo/mbb:"$(cat version)" .
