name: Run tests and build docker image

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Execute tests
        run: ./gradlew clean test
      - name: Build the project
        run: ./gradlew build
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mbb:$(date +%s)
